language: node_js
node_js:
- '4.0'
- '4.1'
- '4.2'
- '5.0'
- '5.1'
- '5.2'
- '5.7'
sudo: false
services:
before_install:
- npm --version
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
notifications:
  email: true
after_failure: cat /home/travis/build/tarlepp/angular-sailsjs-boilerplate-frontend-angular2/npm-debug.log
  only:
  - master
env:
  global:
  # https://github.com/DefinitelyTyped/tsd#tsdrc
  # Token has no scope (read-only access to public information)
  - TSD_GITHUB_TOKEN=TODO
